version: "3"

services:
  flarum:
    image: mondedie/flarum:stable
    container_name: flarum
    env_file:
      - ./flarum.env
    volumes:
      - ./assets:/flarum/app/public/assets
      - ./extensions:/flarum/app/extensions
      - ./storage/logs:/flarum/app/storage/logs
      - ./nginx:/etc/nginx/flarum
    depends_on:
      - mariadb
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.lara_nginx.rule=Host(`flarum.hostbeaver.ru`)"
      - "traefik.http.services.lara_nginx.loadbalancer.server.port=80"

  mariadb:
    image: mariadb:10.5
    container_name: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=36gucoj1
      - MYSQL_DATABASE=flarum
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=36gucoj1
    volumes:
      - /home/admin/db/flarum/mysql/:/var/lib/mysql

networks:
  proxynet:
    external: true
