services:
  flarum:
    image: mondedie/flarum:latest
    container_name: flarum
    env_file:
      - ./flarum.env
    volumes:
      - ./assets:/flarum/app/public/assets
      - ./extensions:/flarum/app/extensions
      - ./storage/logs:/flarum/app/storage/logs
      - ./nginx:/etc/nginx/flarum
#      - ./composer.json:/flarum/app/composer.json
    ports:
      - 80:8888
    depends_on:
      - mariadb
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.flarum.rule=Host(`flarum.hostbeaver.ru`)"

  mariadb:
    image: mariadb:10.5
    container_name: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=36gucoj1
      - MYSQL_DATABASE=flarum
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=36gucoj1
    volumes:
      - /home/admin/db/flarum/mysql/:/var/lib/mysql

networks:
  default:
    name: proxynet
    external: true
